swagger: "2.0"

info:
  version: "0.4.0"
  title: "Trackless API"
  contact:
    name: "wjtje"
    url: "https://www.wjtje.ga"
  license:
    name: "Apache 2.0 License"
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"

paths:
  /group:
    get:
      tags:
        - "group"
      summary: "Get all the groups on the server"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Group"
      security:
        - bearer_token: []
    post:
      tags:
        - "group"
      summary: "Create a new group on the server"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: "object"
            properties:
              groupName:
                type: "string"
      responses:
        "201":
          description: "Created the new group"
          schema:
            type: "object"
            properties:
              group_id:
                type: "integer"
        "400":
          description: "Something is wrong with your input"
      security:
        - bearer_token: []

securityDefinitions:
  bearer_token:
    type: "apiKey"
    name: "api_key"
    in: "header"

definitions:
  Group:
    type: "object"
    properties:
      group_id:
        type: "integer"
      groupName:
        type: "string"
      users:
        type: "array"
        items:
          $ref: "#/definitions/User"
  User:
    type: "object"
    properties:
      user_id:
        type: "integer"
      firstname:
        type: "string"
      lastname:
        type: "string"
      username:
        type: "string"
      group_id:
        type: "integer"
