# This workflow will test the packages for any known vulnerabilities

name: NPM audit

on:
  schedule:
    - cron: '0 12 * * *'

jobs:
  audit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm audit
